name: NPM Publish

on:
    release:
      types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
        cache: 'pnpm'
    - name: PNPM Install
      run: pnpm install --no-frozen-lockfile
    - name: Build
      run: pnpm build
    - name: Publish
      run: pnpm publish --access public --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}