name: NPM Publish

on:
    release:
      types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.5.0
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/
        cache: 'npm'
    - name: NPM Install
      run: npm i
    - name: Build
      run: npm run build
    - name: Publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}